# Generated by Django 4.2.5 on 2023-09-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
    ]
